"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import glob

APP = ['main.py']
DATA_FILES = [('assets', glob.glob('assets/*')), ('models', glob.glob('models/*')), 'game.py', 'utils.py', 'paths.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
